



  -- Tasks --

-- task 1:

-- Write a SQL query to retrieve all the customer information along with the total number of orders 
-- placed by each customer. Display the result in descending order of the number of orders.

SELECT customers.*, COUNT(orders.id) AS total_number_of_order_placed
FROM customers
INNER JOIN orders ON customers.id = orders.customer_id
GROUP BY orders.customer_id ORDER BY total_number_of_order_placed DESC;




-- task 2:

-- Write a SQL query to retrieve the product name, quantity, and total amount 
-- for each order item. Display the result in ascending order of the order ID.

SELECT o.id,p.name, oi.quantity, o.total_amount
FROM products p
INNER JOIN order_items oi ON oi.product_id = p.id
INNER JOIN orders o ON o.id = oi.order_id
ORDER BY o.id ASC;




-- task 3:

-- Write a SQL query to retrieve the total revenue generated by each product category. 
-- Display the category name along with the total revenue in descending order of the revenue.

SELECT c.name AS category_name,SUM(oi.quantity*oi.unit_price) AS revenue
FROM categories c
INNER JOIN products p ON p.category_id = c.id
INNER JOIN order_items oi ON oi.product_id = p.id
GROUP BY p.category_id ORDER BY revenue DESC;




-- task 4:

-- Write a SQL query to retrieve the top 5 customers who have made the highest total purchase amount. 
-- Display the customer name along with the total purchase amount in descending order of the purchase amount.


SELECT c.name AS customer_name,SUM(o.total_amount) AS purchase_amount
FROM customers c
INNER JOIN orders o ON o.customer_id = c.id
GROUP BY o.customer_id ORDER BY purchase_amount DESC LIMIT 5;